Repository kakao-tech-campus-2nd-step3/Team17_BE, pull requests merged in 2024-11, with the labels that each got.

#170 [Week9] 상품 관련 수정
  src/main/java/homeTry/product/controller/MarketController.java
  src/main/java/homeTry/product/dto/request/ProductRequest.java
  src/main/java/homeTry/product/dto/response/ProductResponse.java
  src/main/java/homeTry/product/model/entity/Product.java
  src/main/java/homeTry/product/model/entity/ProductTagMapping.java
  src/main/java/homeTry/product/model/vo/ProductName.java
  src/main/java/homeTry/product/model/vo/StoreName.java
  src/main/java/homeTry/product/repository/ProductRepository.java
  src/main/java/homeTry/product/repository/ProductTagMappingRepository.java
  src/main/java/homeTry/product/service/AdminProductService.java
  src/main/java/homeTry/product/service/ProductService.java
  src/main/java/homeTry/product/service/ProductTagMappingService.java
  src/main/java/homeTry/tag/productTag/service/ProductTagService.java
  src/main/resources/data.sql
Labels: :sparkles: feat, :recycle: refactor

#171 [Week9] Mainpage 조회 일기 부분의 페이지네이션 추가 및 변수명 변경
  src/main/java/homeTry/diary/repository/DiaryRepository.java
  src/main/java/homeTry/diary/service/DiaryService.java
  src/main/java/homeTry/mainPage/dto/response/MainPageResponse.java
  src/main/java/homeTry/tag/productTag/dto/ProductTagDto.java
  src/main/java/homeTry/tag/productTag/dto/request/ProductTagRequest.java
  src/main/java/homeTry/tag/productTag/service/ProductTagService.java
  src/main/java/homeTry/tag/teamTag/dto/TeamTagDTO.java
Labels: :sparkles: feat, :recycle: refactor

#178 [Week 9] Chatting 기능 리팩터링 및 인터셉터 예외 핸들링 고도화
  src/main/java/homeTry/chatting/dto/request/ChattingMessageRequest.java
  src/main/java/homeTry/chatting/dto/response/ChattingMessageResponse.java
  src/main/java/homeTry/chatting/exception/ChattingErrorType.java
  src/main/java/homeTry/chatting/exception/handler/StompInterceptorErrorHandler.java
  src/main/java/homeTry/chatting/exception/internalServerException/NoSuchMemberInDbWithValidTokenException.java
  src/main/java/homeTry/chatting/interceptor/StompInterceptor.java
  src/main/java/homeTry/chatting/model/entity/Chatting.java
  src/main/java/homeTry/chatting/repository/ChattingRepository.java
  src/main/java/homeTry/chatting/service/ChattingService.java
Labels: :recycle: refactor

#179 [Week 9] 쉘 스크립트 파일 리팩터링
  deploy.sh
Labels: :recycle: refactor

#180 [Week 9] 메서드 이름 리팩터링
  src/main/java/homeTry/chatting/service/ChattingService.java
Labels: :recycle: refactor

#181 [Week 9] Member, Chatting 기능 리팩터링
  src/main/java/homeTry/chatting/config/ChattingConfig.java
  src/main/java/homeTry/chatting/exception/ChattingErrorType.java
  src/main/java/homeTry/chatting/exception/handler/StompInterceptorErrorHandler.java
  src/main/java/homeTry/common/config/WebMvcConfig.java
  src/main/java/homeTry/member/controller/MemberController.java
  src/main/java/homeTry/member/dto/response/MyPageResponse.java
  src/main/java/homeTry/member/service/MemberService.java
Labels: :recycle: refactor

#183 [Week9] 관리자 태그 관리 페이지 추가
  build.gradle
  src/main/java/homeTry/diary/service/DiaryService.java
  src/main/java/homeTry/mainPage/controller/MainPageController.java
  src/main/java/homeTry/mainPage/service/MainPageService.java
  src/main/java/homeTry/tag/controller/TagPageController.java
  src/main/java/homeTry/tag/productTag/dto/request/ProductTagRequest.java
  src/main/java/homeTry/tag/productTag/service/ProductTagService.java
  src/main/java/homeTry/tag/teamTag/controller/TeamTagController.java
  src/main/java/homeTry/tag/teamTag/model/entity/TeamTag.java
  src/main/java/homeTry/tag/teamTag/service/TeamTagService.java
  src/main/resources/static/css/styles.css
  src/main/resources/templates/tag/AddProductTag.html
  src/main/resources/templates/tag/AddTeamTag.html
  src/main/resources/templates/tag/ProductTags.html
  src/main/resources/templates/tag/TeamTags.html
Labels: :sparkles: feat

#185 [Week10] isDeprecated 추가
  src/main/java/homeTry/common/entity/BaseEntity.java
Labels: :recycle: refactor

#187 [Week10] BaseEntity 관련 수정
  src/main/java/homeTry/common/entity/BaseEntity.java
  src/main/java/homeTry/product/model/entity/ProductTagMapping.java
  src/main/resources/data.sql
Labels: :recycle: refactor

#188 [Week10] diaryRepository 메서드명 변경
  src/main/java/homeTry/diary/repository/DiaryRepository.java
  src/main/java/homeTry/diary/service/DiaryService.java
Labels: :recycle: refactor

#189 [Week10] 운동 시간 관련 수정
  src/main/java/homeTry/exerciseList/event/ExerciseCreationEvent.java
  src/main/java/homeTry/exerciseList/event/ExerciseCreationEventListener.java
  src/main/java/homeTry/exerciseList/event/ExerciseEventPublisher.java
  src/main/java/homeTry/exerciseList/model/entity/Exercise.java
  src/main/java/homeTry/exerciseList/model/entity/ExerciseHistory.java
  src/main/java/homeTry/exerciseList/model/entity/ExerciseTime.java
  src/main/java/homeTry/exerciseList/repository/ExerciseHistoryRepository.java
  src/main/java/homeTry/exerciseList/repository/ExerciseRepository.java
  src/main/java/homeTry/exerciseList/repository/ExerciseTimeRepository.java
  src/main/java/homeTry/exerciseList/service/ExerciseHistoryService.java
  src/main/java/homeTry/exerciseList/service/ExerciseSchedulerService.java
  src/main/java/homeTry/exerciseList/service/ExerciseService.java
  src/main/java/homeTry/exerciseList/service/ExerciseTimeService.java
Labels: :recycle: refactor

#190 [Week10] Tag에 soft delete 및 중복검사 기능 추가
  src/main/java/homeTry/diary/service/DiaryService.java
  src/main/java/homeTry/mainPage/controller/MainPageController.java
  src/main/java/homeTry/tag/model/entity/Tag.java
  src/main/java/homeTry/tag/productTag/exception/BadRequestException/ProductTagAlreadyExistsException.java
  src/main/java/homeTry/tag/productTag/exception/ProductTagErrorType.java
  src/main/java/homeTry/tag/productTag/model/entity/ProductTag.java
  src/main/java/homeTry/tag/productTag/repository/ProductTagRepository.java
  src/main/java/homeTry/tag/productTag/service/ProductTagService.java
  src/main/java/homeTry/tag/teamTag/exception/BadRequestException/TeamTagAlreadyExistsException.java
  src/main/java/homeTry/tag/teamTag/exception/TeamTagErrorType.java
  src/main/java/homeTry/tag/teamTag/model/entity/TeamTag.java
  src/main/java/homeTry/tag/teamTag/repository/TeamTagRepository.java
  src/main/java/homeTry/tag/teamTag/service/TeamTagService.java
  src/main/resources/data.sql
  src/main/resources/templates/tag/TeamTags.html
Labels: :sparkles: feat

#192 [Week] 상품 관련 수정
  src/main/java/homeTry/product/controller/MarketController.java
  src/main/java/homeTry/product/model/entity/Product.java
  src/main/java/homeTry/product/model/entity/ProductTagMapping.java
  src/main/java/homeTry/product/service/ProductService.java
Labels: :recycle: refactor

#193 [Week 10] 피드백 반영 & Member와 Chatting E2E 테스트 코드 작성 & Member 엔티티 필드 추가
  src/main/java/homeTry/chatting/config/ChattingConfig.java
  src/main/java/homeTry/chatting/endpointHandler/async/ChattingMessageListener.java
  src/main/java/homeTry/chatting/endpointHandler/rest/ChattingController.java
  src/main/java/homeTry/chatting/interceptor/StompInterceptor.java
  src/main/java/homeTry/chatting/model/entity/Chatting.java
  src/main/java/homeTry/chatting/service/ChattingService.java
  src/main/java/homeTry/common/auth/LoginMemberArgumentResolver.java
  src/main/java/homeTry/common/auth/jwt/JwtAuth.java
  src/main/java/homeTry/common/auth/jwt/JwtUtil.java
  src/main/java/homeTry/common/auth/kakaoAuth/controller/KakaoAuthController.java
  src/main/java/homeTry/common/config/WebMvcConfig.java
  src/main/java/homeTry/common/interceptor/JwtInterceptor.java
  src/main/java/homeTry/member/model/entity/Member.java
  src/main/java/homeTry/member/model/enums/Role.java
  src/main/java/homeTry/member/service/MemberService.java
  src/main/resources/data.sql
  src/test/java/homeTry/chatting/ChattingTest.java
  src/test/java/homeTry/common/config/CorsTest.java
  src/test/java/homeTry/member/MemberTest.java
Labels: :sparkles: feat, :recycle: refactor

#194 [Week10] MemberService의 Role 기능 추가
  src/main/java/homeTry/member/model/entity/Member.java
  src/main/java/homeTry/member/service/MemberService.java
Labels: :sparkles: feat

#195 [Week10] MemberDTO - Role 필드 추가
  src/main/java/homeTry/common/auth/kakaoAuth/service/KakaoAuthService.java
  src/main/java/homeTry/common/auth/kakaoAuth/service/KakaoClientService.java
  src/main/java/homeTry/member/dto/MemberDTO.java
  src/main/java/homeTry/member/service/MemberService.java
Labels: :sparkles: feat

#196 [Week10] 상품 관리자 관련 수정
  src/main/java/homeTry/product/controller/AdminProductController.java
  src/main/java/homeTry/product/dto/request/ProductRequest.java
  src/main/java/homeTry/product/dto/response/ProductAdminResponse.java
  src/main/java/homeTry/product/exception/ProductErrorType.java
  src/main/java/homeTry/product/exception/badRequestException/MissingProductTagException.java
  src/main/java/homeTry/product/exception/badRequestException/UnauthorizedAccessException.java
  src/main/java/homeTry/product/repository/ProductRepository.java
  src/main/java/homeTry/product/repository/ProductTagMappingRepository.java
  src/main/java/homeTry/product/service/AdminProductService.java
  src/main/java/homeTry/product/service/ProductTagMappingService.java
Labels: :sparkles: feat, :recycle: refactor

#197 [Week10] 운동 관련 E2E 테스트 코드 및 수정
  src/main/java/homeTry/exerciseList/model/entity/ExerciseTime.java
  src/main/java/homeTry/exerciseList/service/ExerciseHistoryService.java
  src/main/java/homeTry/exerciseList/service/ExerciseSchedulerService.java
  src/main/java/homeTry/exerciseList/service/ExerciseTimeService.java
  src/test/java/homeTry/exerciseList/ExerciseTest.java
  src/test/java/homeTry/exerciseList/service/ExerciseSchedulerServiceTest.java
Labels: :recycle: refactor

#199 [Week10] CORS 테스트 코드 버그 수정
  src/test/java/homeTry/common/config/CorsTest.java
Labels: :bug: bug

#200 [Week10] H2 Mem -> MySQL 로 마이그레이션
  build.gradle
  src/main/resources/application.properties
Labels: :recycle: refactor

#201 [Week10] 테스트 코드 및 관리자 권한 확인 로직 추가
  src/main/java/homeTry/diary/controller/DiaryController.java
  src/main/java/homeTry/diary/repository/DiaryRepository.java
  src/main/java/homeTry/diary/service/DiaryService.java
  src/main/java/homeTry/tag/controller/TagPageController.java
  src/main/java/homeTry/tag/exception/TagErrorType.java
  src/main/java/homeTry/tag/exception/badRequestException/ForbiddenTagAccessException.java
  src/main/java/homeTry/tag/productTag/controller/ProductTagController.java
  src/main/java/homeTry/tag/productTag/service/ProductTagService.java
  src/main/java/homeTry/tag/teamTag/controller/TeamTagController.java
  src/main/java/homeTry/tag/teamTag/service/TeamTagService.java
  src/test/java/homeTry/diary/DiaryTest.java
  src/test/java/homeTry/mainPage/MainPageTest.java
  src/test/java/homeTry/tag/TagPageTest.java
  src/test/java/homeTry/tag/productTag/ProductTagTest.java
  src/test/java/homeTry/tag/teamTag/TeamTagTest.java
Labels: :sparkles: feat, :recycle: refactor

#202 [Week10] 상품 및 운동 관련 수정
  gradlew
  src/main/java/homeTry/exerciseList/repository/ExerciseHistoryRepository.java
  src/main/java/homeTry/exerciseList/repository/ExerciseRepository.java
  src/main/java/homeTry/exerciseList/repository/ExerciseTimeRepository.java
  src/main/java/homeTry/exerciseList/service/ExerciseHistoryService.java
  src/main/java/homeTry/exerciseList/service/ExerciseSchedulerService.java
  src/main/java/homeTry/exerciseList/service/ExerciseService.java
  src/main/java/homeTry/exerciseList/service/ExerciseTimeService.java
  src/main/java/homeTry/product/controller/AdminProductController.java
  src/main/java/homeTry/product/controller/AdminProductViewController.java
  src/main/java/homeTry/product/controller/MarketController.java
  src/main/java/homeTry/product/dto/request/ProductRequest.java
  src/main/java/homeTry/product/model/entity/ProductTagMapping.java
  src/main/java/homeTry/product/service/AdminProductService.java
  src/main/java/homeTry/product/service/ProductService.java
  src/main/resources/data.sql
  src/main/resources/templates/product/productAdd.html
  src/main/resources/templates/product/productList.html
  src/test/java/homeTry/product/AdminProductTest.java
  src/test/java/homeTry/product/MarketTest.java
Labels: :sparkles: feat, :recycle: refactor

#203 [Week10] refactor: 메서드 명 변경
  src/main/java/homeTry/tag/productTag/service/ProductTagService.java
Labels: :recycle: refactor

#204 [Week10] 랜덤 닉네임으로 회원가입 하는 기능 추가
  src/main/java/homeTry/common/auth/kakaoAuth/dto/KakaoMemberInfoDTO.java
  src/main/java/homeTry/common/auth/kakaoAuth/service/KakaoAuthService.java
  src/main/java/homeTry/common/auth/kakaoAuth/service/KakaoClientService.java
  src/main/java/homeTry/member/service/MemberService.java
  src/main/java/homeTry/member/utils/RandomNicknameGenerator.java
  src/main/resources/data.sql
  src/test/java/homeTry/chatting/ChattingTest.java
Labels: :sparkles: feat

#205 [Week10] data.sql 버그 수정
  src/main/resources/data.sql
Labels: :bug: bug

#207 [Week10] 운동 인덱스 추가 및 코드 정리
  src/main/java/homeTry/exerciseList/model/entity/ExerciseTime.java
  src/main/java/homeTry/exerciseList/service/ExerciseTimeService.java
  src/test/java/homeTry/exerciseList/ExerciseTest.java
Labels: :recycle: refactor

#208 [Week10] 회원 탈퇴 기능 구현
  src/main/java/homeTry/member/controller/MemberController.java
  src/main/java/homeTry/member/model/entity/Member.java
  src/main/java/homeTry/member/model/vo/Email.java
  src/main/java/homeTry/member/model/vo/Nickname.java
  src/main/java/homeTry/member/service/MemberService.java
  src/main/java/homeTry/member/service/MemberWithdrawService.java
  src/main/resources/data.sql
Labels: :sparkles: feat

#209 [Week10] 운동 생성 시 시작시간 조정
  src/main/java/homeTry/exerciseList/model/entity/ExerciseTime.java
Labels: :bug: bug

#210 [Week10] refactor: 시간 관련 버그 수정
  src/main/java/homeTry/common/constants/DateTimeUtil.java
  src/main/java/homeTry/exerciseList/model/entity/ExerciseTime.java
  src/main/java/homeTry/exerciseList/service/ExerciseTimeService.java
Labels: :bug: bug

#212 [Week10] Diary, Tag에 index 적용
  src/main/java/homeTry/diary/model/entity/Diary.java
  src/main/java/homeTry/mainPage/service/MainPageService.java
  src/main/java/homeTry/tag/productTag/model/entity/ProductTag.java
  src/main/java/homeTry/tag/teamTag/model/entity/TeamTag.java
Labels: :recycle: refactor

#217 [Week10] MainPage pagable 객체 기본 사이즈 변경
  src/main/java/homeTry/mainPage/controller/MainPageController.java
Labels: :recycle: refactor

#218 [Week10] 운동 히스토리 관련 수정
  src/main/java/homeTry/exerciseList/exception/ExerciseErrorType.java
  src/main/java/homeTry/exerciseList/model/entity/ExerciseHistory.java
  src/main/java/homeTry/exerciseList/model/entity/ExerciseTime.java
  src/main/java/homeTry/exerciseList/service/ExerciseHistoryService.java
  src/main/java/homeTry/product/controller/AdminProductViewController.java
  src/main/java/homeTry/product/exception/ProductErrorType.java
  src/main/resources/data.sql
Labels: :recycle: refactor

#223 [Week10] Tag가 softDeletableEntity를 상속하도록 변경
  src/main/java/homeTry/tag/model/entity/Tag.java
Labels: :recycle: refactor

#224 [Week10] 운동 및 운동 기록 조회 쿼리문 수정
  src/main/java/homeTry/exerciseList/repository/ExerciseHistoryRepository.java
  src/main/java/homeTry/exerciseList/repository/ExerciseRepository.java
  src/main/java/homeTry/exerciseList/repository/ExerciseTimeRepository.java
  src/main/java/homeTry/exerciseList/service/ExerciseService.java
Labels: :recycle: refactor

#225 [Week10] is_deprecated 부분 에러 수정
  src/main/java/homeTry/exerciseList/repository/ExerciseRepository.java
  src/main/java/homeTry/exerciseList/repository/ExerciseTimeRepository.java
  src/main/java/homeTry/exerciseList/service/ExerciseService.java
  src/main/resources/data.sql
Labels: :recycle: refactor

#226 [Week10] 필요 없는 메서드 제거
  src/main/java/homeTry/member/service/MemberService.java
Labels: :fire: remove

#227 [Week10] data.sql 리팩터링
  src/main/resources/data.sql
Labels: :recycle: refactor

#221 [Week10] 관리자 페이지 구현
  src/main/java/homeTry/admin/controller/AdminPageController.java
  src/main/java/homeTry/admin/dto/request/AdminCodeRequest.java
  src/main/java/homeTry/admin/service/AdminPageService.java
  src/main/java/homeTry/common/config/WebMvcConfig.java
  src/main/java/homeTry/common/interceptor/AdminInterceptor.java
  src/main/resources/static/css/styles.css
  src/main/resources/templates/adminPage.html
  src/main/resources/templates/index.html
Labels: :sparkles: feat, :recycle: refactor

#229 [Week10] data.sql 추가적인 리팩터링
  src/main/resources/data.sql
Labels: :recycle: refactor

#231 [Week10] adminInterceptor 구현에 따른 Tag내 관리자 권한 확인 로직 제거
  src/main/java/homeTry/common/config/WebMvcConfig.java
  src/main/java/homeTry/tag/controller/TagPageController.java
  src/main/java/homeTry/tag/productTag/controller/ProductTagController.java
  src/main/java/homeTry/tag/productTag/service/ProductTagService.java
  src/main/java/homeTry/tag/teamTag/controller/TeamTagController.java
  src/main/java/homeTry/tag/teamTag/service/TeamTagService.java
Labels: :recycle: refactor

#232 [Week10] 운동 저장 부분 수정 및 인터셉터 구현에 따른 상품 관리자 권한 확인 로직 제거
  src/main/java/homeTry/exerciseList/event/ExerciseCreationEventListener.java
  src/main/java/homeTry/exerciseList/model/entity/ExerciseTime.java
  src/main/java/homeTry/exerciseList/service/ExerciseSchedulerService.java
  src/main/java/homeTry/exerciseList/service/ExerciseTimeHelper.java
  src/main/java/homeTry/exerciseList/service/ExerciseTimeService.java
  src/main/java/homeTry/product/controller/AdminProductController.java
  src/main/java/homeTry/product/controller/AdminProductViewController.java
  src/main/java/homeTry/product/model/entity/Product.java
  src/main/java/homeTry/product/model/entity/ProductTagMapping.java
  src/main/java/homeTry/product/repository/ProductRepository.java
  src/main/java/homeTry/product/service/AdminProductService.java
  src/main/java/homeTry/product/service/ProductService.java
Labels: :recycle: refactor

#234 [Week10] 회원 탈퇴 기능 완성 & FE 배포 url 반영 & 에러 로깅 기능 추가
  src/main/java/homeTry/chatting/config/ChattingConfig.java
  src/main/java/homeTry/chatting/dto/response/ChattingMessageResponse.java
  src/main/java/homeTry/chatting/interceptor/StompInterceptor.java
  src/main/java/homeTry/chatting/repository/ChattingRepository.java
  src/main/java/homeTry/chatting/service/ChattingService.java
  src/main/java/homeTry/common/auth/LoginMemberArgumentResolver.java
  src/main/java/homeTry/common/auth/kakaoAuth/service/KakaoAuthService.java
  src/main/java/homeTry/common/config/WebMvcConfig.java
  src/main/java/homeTry/common/exception/CommonErrorType.java
  src/main/java/homeTry/common/exception/GlobalExceptionHandler.java
  src/main/java/homeTry/member/exception/MemberErrorType.java
  src/main/java/homeTry/member/exception/badRequestException/InactivatedMemberException.java
  src/main/java/homeTry/member/model/entity/Member.java
  src/main/java/homeTry/member/service/MemberService.java
  src/main/java/homeTry/member/service/MemberTeamWithdrawService.java
  src/main/java/homeTry/member/service/MemberWithdrawService.java
  src/main/java/homeTry/team/service/TeamWithdrawService.java
  src/main/resources/data.sql
Labels: :sparkles: feat, :recycle: refactor

#235 [Week10] 응답코드 리팩터링
  src/main/java/homeTry/member/exception/MemberErrorType.java
Labels: :recycle: refactor

#236 fix: CORS 에러 수정
  src/main/java/homeTry/common/config/WebMvcConfig.java
Labels: :bug: bug

#237 [Week10] 태그 관리 페이지내에 돌아가기 버튼 추가
  src/main/resources/templates/tag/AddProductTag.html
  src/main/resources/templates/tag/AddTeamTag.html
  src/main/resources/templates/tag/ProductTags.html
  src/main/resources/templates/tag/TeamTags.html
Labels: :recycle: refactor

#239 [Week11] 패키지 구조 통일 및 swagger 의존성 추가
  build.gradle
  src/main/java/homeTry/diary/exception/badRequestException/DiaryNotFoundException.java
  src/main/java/homeTry/diary/service/DiaryService.java
  src/main/java/homeTry/product/service/AdminProductService.java
  src/main/java/homeTry/product/service/ProductTagMappingService.java
  src/main/java/homeTry/tag/productTag/exception/badRequestException/ProductTagAlreadyExistsException.java
  src/main/java/homeTry/tag/productTag/exception/badRequestException/ProductTagNotFoundException.java
  src/main/java/homeTry/tag/productTag/service/ProductTagService.java
  src/main/java/homeTry/tag/teamTag/exception/badRequestException/TeamTagAlreadyExistsException.java
  src/main/java/homeTry/tag/teamTag/exception/badRequestException/TeamTagNotFoundException.java
  src/main/java/homeTry/tag/teamTag/service/TeamTagService.java
Labels: :recycle: refactor

#240 [Week11] 운동 시간 관련 버그 해결
  src/main/java/homeTry/exerciseList/service/ExerciseTimeService.java
  src/main/java/homeTry/product/controller/AdminProductController.java
  src/main/java/homeTry/product/controller/AdminProductViewController.java
  src/test/java/homeTry/exerciseList/service/ExerciseTimeServiceTest.java
  src/test/java/homeTry/product/AdminProductTest.java
  src/test/java/homeTry/product/AdminProductViewTest.java
Labels: :recycle: refactor

#242 [Week11] refactor: 변수명 명시
  src/main/java/homeTry/product/controller/AdminProductViewController.java
  src/main/java/homeTry/tag/controller/TagPageController.java
Labels: :recycle: refactor

#243 [Week11] 관리자 페이지 구현
  src/main/java/homeTry/admin/controller/AdminMainPageController.java
  src/main/java/homeTry/admin/controller/AdminMainPageLoginController.java
  src/main/java/homeTry/admin/controller/AdminPageController.java
  src/main/java/homeTry/admin/exception/AdminErrorType.java
  src/main/java/homeTry/admin/exception/badReqeustException/InvalidAdminCodeException.java
  src/main/java/homeTry/admin/service/AdminPageService.java
  src/main/java/homeTry/common/auth/kakaoAuth/controller/KakaoAuthRestController.java
  src/main/java/homeTry/common/auth/kakaoAuth/controller/KakaoAuthSSRController.java
  src/main/java/homeTry/common/config/WebMvcConfig.java
  src/main/java/homeTry/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/homeTry/common/interceptor/AdminInterceptor.java
  src/main/java/homeTry/exerciseList/controller/ExerciseController.java
  src/main/resources/application-kakao-login.properties
  src/main/resources/static/image/kakao_login_medium_narrow.png
  src/main/resources/static/js/adminPromote.js
  src/main/resources/static/js/main.js
  src/main/resources/templates/adminKakaoLoginResult.html
  src/main/resources/templates/adminMainPage.html
  src/main/resources/templates/adminMainPageLogin.html
  src/main/resources/templates/adminPromote.html
  src/main/resources/templates/application-secret.properties
  src/main/resources/templates/index.html
  src/main/resources/templates/tag/AddTeamTag.html
Labels: :sparkles: feat

#248 [Week10] kakao redirect url 변경
  src/main/resources/application-prod-kakao-login.properties
  src/main/resources/templates/admin/adminKakaoLoginResult.html
Labels: :recycle: refactor

#247 [Week11] 상품 관련 수정 및 스웨거 적용
  src/main/java/homeTry/exerciseList/controller/ExerciseController.java
  src/main/java/homeTry/product/controller/AdminProductViewController.java
  src/main/java/homeTry/product/controller/MarketController.java
  src/main/java/homeTry/product/exception/ProductErrorType.java
  src/main/java/homeTry/product/exception/badRequestException/ForbiddenProductAccessException.java
  src/main/java/homeTry/product/exception/badRequestException/InvalidMemberException.java
  src/main/java/homeTry/product/model/entity/Product.java
  src/main/java/homeTry/product/repository/ProductRepository.java
  src/main/java/homeTry/product/service/AdminProductService.java
  src/main/java/homeTry/product/service/ProductService.java
  src/main/java/homeTry/product/service/ProductTagMappingService.java
  src/main/resources/data.sql
  src/main/resources/templates/product/productEdit.html
  src/main/resources/templates/product/productList.html
Labels: :sparkles: feat, :recycle: refactor

#250 [Week11] 반응형 -> px로 리팩터링
  src/main/resources/static/css/adminAuthority.css
  src/main/resources/static/css/adminMainPage.css
  src/main/resources/static/css/adminPromote.css
  src/main/resources/static/css/styles.css
Labels: :recycle: refactor

#251 [Week11] 상품 edit 버튼 안눌리는 버그 해결 및 관리자 상품 uri 변경
  src/main/java/homeTry/product/controller/AdminProductViewController.java
  src/main/java/homeTry/product/dto/request/ProductRequest.java
  src/main/java/homeTry/product/model/vo/ProductName.java
  src/main/resources/templates/product/productAdd.html
  src/main/resources/templates/product/productEdit.html
  src/main/resources/templates/product/productList.html
Labels: :bug: bug

#252 [Week11] 태그관리 uri 수정 및 사용하지 않는 컨트롤러 삭제
  src/main/java/homeTry/tag/controller/TagPageController.java
  src/main/java/homeTry/tag/productTag/controller/ProductTagController.java
  src/main/java/homeTry/tag/teamTag/controller/TeamTagController.java
  src/main/resources/templates/admin/adminPage.html
  src/main/resources/templates/tag/AddProductTag.html
  src/main/resources/templates/tag/AddTeamTag.html
  src/main/resources/templates/tag/ProductTags.html
  src/main/resources/templates/tag/TeamTags.html
Labels: :recycle: refactor

#253 [Week11] 상품 삭제 더 RESTful 하도록 리펙터링
  src/main/java/homeTry/admin/exception/AdminErrorType.java
  src/main/java/homeTry/common/config/WebMvcConfig.java
  src/main/java/homeTry/member/dto/MemberDTO.java
  src/main/java/homeTry/member/service/MemberService.java
  src/main/java/homeTry/product/controller/AdminProductRestController.java
  src/main/java/homeTry/product/controller/AdminProductViewController.java
  src/main/resources/static/js/main.js
  src/main/resources/static/js/productAdd.js
  src/main/resources/static/js/productList.js
  src/main/resources/templates/admin/adminPage.html
  src/main/resources/templates/product/productAdd.html
  src/main/resources/templates/product/productList.html
  src/main/resources/templates/tag/AddProductTag.html
  src/main/resources/templates/tag/ProductTags.html
  src/main/resources/templates/tag/TeamTags.html
Labels: :recycle: refactor

#255 [Week11] 시간 관련 버그 수정
  src/main/java/homeTry/exerciseList/dto/response/ExerciseResponse.java
  src/main/java/homeTry/exerciseList/exception/ExerciseErrorType.java
  src/main/java/homeTry/exerciseList/exception/badRequestException/DailyExerciseTimeLimitExceededException.java
  src/main/java/homeTry/exerciseList/exception/badRequestException/ExerciseTimeLimitExceededException.java
  src/main/java/homeTry/exerciseList/service/ExerciseSchedulerService.java
  src/main/java/homeTry/exerciseList/service/ExerciseTimeService.java
  src/test/java/homeTry/exerciseList/service/ExerciseTimeServiceTest.java
  src/test/java/homeTry/product/AdminProductViewTest.java
Labels: :bug: bug

#256 [Week11] Swagger 적용 및 redirectURI 수정
  src/main/java/homeTry/diary/controller/DiaryController.java
  src/main/java/homeTry/mainPage/controller/MainPageController.java
  src/main/java/homeTry/tag/controller/TagPageController.java
  src/test/java/homeTry/tag/TagPageTest.java
  src/test/java/homeTry/tag/productTag/ProductTagTest.java
  src/test/java/homeTry/tag/teamTag/TeamTagTest.java
Labels: :sparkles: feat, :recycle: refactor

#257 [Week11] 12시간 초과 운동에 대한 처리 수정 및 테스트 코드 수정
  src/main/java/homeTry/exerciseList/model/entity/ExerciseTime.java
  src/main/java/homeTry/exerciseList/service/ExerciseTimeService.java
  src/test/java/homeTry/product/AdminProductViewTest.java
Labels: :recycle: refactor

#258 feat: 팀 기능 테스트 구현
  src/test/java/homeTry/team/TeamTest.java
Labels: :sparkles: feat

#260 [Week11] 스웨거 수정
  src/main/java/homeTry/exerciseList/controller/ExerciseController.java
  src/main/java/homeTry/product/controller/AdminProductRestController.java
  src/main/java/homeTry/product/controller/MarketController.java
Labels: :scroll: documentation

#262 [Week11] Swagger 작성, url 수정, /docs -> /swagger-ui/index.html 리다이렉트 구현
  build.gradle
  src/main/java/homeTry/admin/controller/rest/AdminPageRestController.java
  src/main/java/homeTry/admin/controller/view/AdminAuthorityController.java
  src/main/java/homeTry/admin/controller/view/AdminMainPageController.java
  src/main/java/homeTry/admin/controller/view/AdminPageViewController.java
  src/main/java/homeTry/chatting/config/ChattingConfig.java
  src/main/java/homeTry/chatting/endpointHandler/rest/ChattingController.java
  src/main/java/homeTry/common/auth/kakaoAuth/controller/rest/KakaoAuthRestController.java
  src/main/java/homeTry/common/auth/kakaoAuth/controller/view/KakaoAuthSSRController.java
  src/main/java/homeTry/docs/SwaggerRedirectController.java
  src/main/java/homeTry/member/controller/MemberController.java
  src/main/java/homeTry/member/dto/MemberDTO.java
  src/main/java/homeTry/product/controller/rest/AdminProductRestController.java
  src/main/java/homeTry/product/controller/rest/MarketController.java
  src/main/java/homeTry/product/controller/view/AdminProductViewController.java
  src/main/resources/application-dev-kakao-login.properties
  src/main/resources/application-prod-kakao-login.properties
  src/main/resources/application.properties
Labels: :scroll: documentation, :sparkles: feat, :recycle: refactor

#261 [Week11] 어노테이션 순서 변경
  src/main/java/homeTry/diary/controller/DiaryController.java
  src/main/java/homeTry/mainPage/controller/MainPageController.java
Labels: :scroll: documentation

#263 [Week11] 팀 탈퇴 테스트 구현
  src/test/java/homeTry/chatting/ChattingTest.java
  src/test/java/homeTry/member/MemberTest.java
Labels: :sparkles: feat

#264 [Week11] 클래스 간 결합력 최소화
  src/main/java/homeTry/chatting/repository/ChattingRepository.java
  src/main/java/homeTry/chatting/service/ChattingService.java
  src/main/java/homeTry/team/repository/TeamMemberMappingRepository.java
  src/main/java/homeTry/team/service/TeamMemberMappingService.java
Labels: :hammer: enhancement, :recycle: refactor

#267 [Week11] 랜덤 닉네임 생성기 -> thread-safe 하게 리팩터링
  src/main/java/homeTry/chatting/interceptor/StompInterceptor.java
  src/main/java/homeTry/member/utils/RandomNicknameGenerator.java
Labels: :hammer: enhancement, :recycle: refactor

#266 [Week11] 상품 관리자 페이지 내 버그 수정
  src/main/java/homeTry/common/config/SwaggerConfig.java
  src/main/java/homeTry/docs/SwaggerRedirectController.java
  src/main/resources/static/js/productEdit.js
  src/main/resources/templates/product/productEdit.html
  src/main/resources/templates/product/productList.html
Labels: :bug: bug, :scroll: documentation, :recycle: refactor

#268 [Week11] 태그 관리 기능 리팩토링 및 swagger 적용
  src/main/java/homeTry/tag/controller/TagPageController.java
  src/main/java/homeTry/tag/controller/rest/TagRestController.java
  src/main/java/homeTry/tag/controller/view/AdminTagViewController.java
  src/main/java/homeTry/tag/productTag/model/entity/ProductTag.java
  src/main/java/homeTry/tag/productTag/repository/ProductTagRepository.java
  src/main/java/homeTry/tag/productTag/service/ProductTagService.java
  src/main/java/homeTry/tag/teamTag/model/entity/TeamTag.java
  src/main/java/homeTry/tag/teamTag/repository/TeamTagRepository.java
  src/main/java/homeTry/tag/teamTag/service/TeamTagService.java
  src/main/resources/static/js/tag/ProductTagDelete.js
  src/main/resources/static/js/tag/productTagAdd.js
  src/main/resources/static/js/tag/teamTagAdd.js
  src/main/resources/static/js/tag/teamTagDelete.js
  src/main/resources/templates/tag/AddProductTag.html
  src/main/resources/templates/tag/AddTeamTag.html
  src/main/resources/templates/tag/ProductTags.html
  src/main/resources/templates/tag/TeamTags.html
Labels: :scroll: documentation, :sparkles: feat, :recycle: refactor

#269 [Week11] Swagger 어노테이션 순서 변경 및 data.sql 오타 수정
  src/main/java/homeTry/team/controller/TeamController.java
  src/main/resources/data.sql
Labels: :scroll: documentation

#270 [Week11] 상품 버튼을 이미지로 리팩터링
  src/main/resources/static/css/productAdd.css
  src/main/resources/static/css/productList.css
  src/main/resources/static/image/add.png
  src/main/resources/static/image/edit.png
  src/main/resources/static/image/previous.png
  src/main/resources/static/image/remove.png
  src/main/resources/static/image/save.png
  src/main/resources/templates/product/productAdd.html
  src/main/resources/templates/product/productList.html
Labels: :recycle: refactor

#271 [Week11] 상품 edit 디자인 리팩터링
  src/main/resources/static/css/productEdit.css
  src/main/resources/static/js/productEdit.js
  src/main/resources/templates/product/productEdit.html
Labels: :recycle: refactor

#273 [Week11] 회원 탈퇴할 때 카카오 로그인 unlink 하는 기능 구현
  src/main/java/homeTry/common/auth/kakaoAuth/client/KakaoApiClient.java
  src/main/java/homeTry/common/auth/kakaoAuth/config/KakaoAuthConfig.java
  src/main/java/homeTry/common/auth/kakaoAuth/dto/KakaoMemberInfoDTO.java
  src/main/java/homeTry/common/auth/kakaoAuth/dto/KakaoMemberWithdrawDTO.java
  src/main/java/homeTry/common/auth/kakaoAuth/service/KakaoClientService.java
  src/main/java/homeTry/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/homeTry/member/model/entity/Member.java
  src/main/java/homeTry/member/service/MemberService.java
  src/main/java/homeTry/member/service/MemberWithdrawService.java
  src/main/java/homeTry/product/controller/rest/AdminProductRestController.java
  src/main/resources/application-dev-kakao-login.properties
  src/main/resources/application-prod-kakao-login.properties
  src/main/resources/static/js/productAdd.js
  src/main/resources/static/js/productEdit.js
  src/main/resources/templates/product/productEdit.html
Labels: :sparkles: feat, :recycle: refactor

#274 [Week11] MySQL로 마이그레이션
  build.gradle
  src/main/resources/application.properties
Labels: :recycle: refactor

#275 [Week11] 관리자 페이지 디자인 개선
  src/main/java/homeTry/tag/controller/rest/TagRestController.java
  src/main/java/homeTry/tag/controller/view/AdminTagViewController.java
  src/main/resources/static/css/admin/adminAuthority.css
  src/main/resources/static/css/admin/adminMainPage.css
  src/main/resources/static/css/admin/adminPromote.css
  src/main/resources/static/css/product/productAdd.css
  src/main/resources/static/css/product/productEdit.css
  src/main/resources/static/css/product/productList.css
  src/main/resources/static/css/tag/addProductTag.css
  src/main/resources/static/css/tag/addTeamTag.css
  src/main/resources/static/css/tag/productTags.css
  src/main/resources/static/css/tag/teamTags.css
  src/main/resources/static/js/admin/adminAuthority.js
  src/main/resources/static/js/admin/adminMainMage.js
  src/main/resources/static/js/admin/adminPromote.js
  src/main/resources/static/js/product/productAdd.js
  src/main/resources/static/js/product/productEdit.js
  src/main/resources/static/js/product/productList.js
  src/main/resources/static/js/tag/productTagDelete.js
  src/main/resources/templates/admin/adminAuthority.html
  src/main/resources/templates/admin/adminMain.html
  src/main/resources/templates/admin/adminPromote.html
  src/main/resources/templates/product/productAdd.html
  src/main/resources/templates/product/productEdit.html
  src/main/resources/templates/product/productList.html
  src/main/resources/templates/tag/AddProductTag.html
  src/main/resources/templates/tag/AddTeamTag.html
  src/main/resources/templates/tag/ProductTags.html
  src/main/resources/templates/tag/TeamTags.html
  src/main/resources/templates/tag/addProductTag.html
  src/main/resources/templates/tag/addTeamTag.html
  src/main/resources/templates/tag/productTags.html
  src/main/resources/templates/tag/teamTags.html
Labels: :recycle: refactor

#276 [Week11] 관리자 상품 수정 버그 해결
  src/main/java/homeTry/product/service/AdminProductService.java
  src/main/java/homeTry/product/service/ProductTagMappingService.java
Labels: :bug: bug

#278 [Week11] 개발환경 - H2 DB, 배포환경 - MySQL 사용하도록 구현
  build.gradle
  src/main/resources/application-dev-kakao-login.properties
  src/main/resources/application-dev.properties
  src/main/resources/application-prod-kakao-login.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: :sparkles: feat

#280 [Week11] 개발 환경에 data-dev.sql 사용하는 기능 추가
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/data-dev.sql
  src/main/resources/data.sql
Labels: :sparkles: feat

#279 [Week11] 태그 테스트 수정
  src/test/java/homeTry/tag/TagPageTest.java
Labels: :recycle: refactor

#281 [Week11] 기본 프로필 dev로 변경
  src/main/resources/application.properties
Labels: :recycle: refactor

#282 [Week11] data.sql을 schema로 설정했던 버그 수정
  src/main/resources/application-dev.properties
Labels: :bug: bug

#283 [Week11] 테스트 코드 수정
  src/test/java/homeTry/exerciseList/ExerciseTest.java
  src/test/java/homeTry/exerciseList/service/ExerciseSchedulerServiceTest.java
  src/test/java/homeTry/exerciseList/service/ExerciseTimeServiceTest.java
  src/test/java/homeTry/product/AdminProductViewTest.java
  src/test/java/homeTry/product/MarketTest.java
Labels: :recycle: refactor

#284 [Week11] 채팅 시간 순으로 조회 안되는 버그 해결
  src/main/java/homeTry/chatting/endpointHandler/rest/ChattingController.java
  src/main/resources/data-dev.sql
Labels: :bug: bug

#287 [Week11] 채팅 메세지 길이 500자 제한하는 기능 구현
  src/main/java/homeTry/chatting/exception/handler/ChattingExceptionHandler.java
  src/main/java/homeTry/chatting/model/entity/Chatting.java
  src/main/java/homeTry/chatting/model/vo/Message.java
Labels: :sparkles: feat

#289 [Week11] 상품 관리자 수정 및 전체 운동 시간 제한 수정
  src/main/java/homeTry/exerciseList/exception/ExerciseErrorType.java
  src/main/java/homeTry/exerciseList/model/entity/ExerciseTime.java
  src/main/java/homeTry/exerciseList/service/ExerciseTimeService.java
  src/main/java/homeTry/product/model/entity/ProductTagMapping.java
  src/main/java/homeTry/product/service/ProductTagMappingService.java
Labels: :recycle: refactor

#291 [Week11] 일기 유효성 검사 수정
  img/erd.png
  src/main/java/homeTry/diary/model/vo/Memo.java
Labels: :recycle: refactor

#292 [Week11] 상품 관리 페이지에서 다음 페이지로 못가던 버그 해결
  src/main/resources/templates/product/productList.html
Labels: :bug: bug

#293 [Week11] 채팅 조회 디폴트 값 내림차순으로 리팩터링
  src/main/java/homeTry/chatting/endpointHandler/rest/ChattingController.java
Labels: :recycle: refactor

#294 [Week11] 안쓰는 import 문 및 메서드 정리
  src/main/java/homeTry/exerciseList/service/ExerciseSchedulerService.java
  src/main/java/homeTry/product/controller/rest/AdminProductRestController.java
  src/main/java/homeTry/product/service/ProductTagMappingService.java
Labels: :fire: remove
