Repository kakao-tech-campus-2nd-step3/Team17_BE, pull requests merged in 2024-09, with the labels that each got.

#38 [Week4] 디렉토리 정리
  src/main/java/homeTry/auth/kakaoAuth/dto/KakaoMemberInfoDTO.java
  src/main/java/homeTry/auth/kakaoAuth/dto/TokenResponseDTO.java
  src/main/java/homeTry/member/dto/MemberDTO.java
  src/main/java/homeTry/member/dto/MyPageDTO.java
Labels: :recycle: refactor

#42 [Week4] 디렉토리 정리
  src/main/java/homeTry/auth/JwtAuth.java
  src/main/java/homeTry/auth/kakaoAuth/service/KakaoAuthService.java
  src/main/java/homeTry/auth/kakaoAuth/service/KakaoTokenService.java
  src/main/java/homeTry/member/service/MemberService.java
Labels: :recycle: refactor

#44 [Week4] 토큰 인증 인터셉터 & Argument Resolver 구현
  src/main/java/homeTry/annotation/LoginMember.java
  src/main/java/homeTry/auth/LoginMemberArgumentResolver.java
  src/main/java/homeTry/config/WebMvcConfig.java
  src/main/java/homeTry/interceptor/JwtInterceptor.java
Labels: :sparkles: feat

#49 [Week4] week3 리뷰 기반 리팩토링 및 주간, 월간 통계 기능 구현
  src/main/java/homeTry/exerciseList/controller/ExerciseListController.java
  src/main/java/homeTry/exerciseList/model/entity/ExerciseList.java
  src/main/java/homeTry/exerciseList/model/vo/ActiveStatus.java
  src/main/java/homeTry/exerciseList/model/vo/DeprecatedStatus.java
  src/main/java/homeTry/exerciseList/repository/ExerciseListRepository.java
  src/main/java/homeTry/exerciseList/service/ExerciseListService.java
Labels: :sparkles: feat, :recycle: refactor

#60 [Week4] 운동리스트 버그 수정 및 Member와 연결 구현
  src/main/java/homeTry/exerciseList/controller/ExerciseListController.java
  src/main/java/homeTry/exerciseList/dto/ExerciseListRequest.java
  src/main/java/homeTry/exerciseList/model/entity/ExerciseList.java
  src/main/java/homeTry/exerciseList/repository/ExerciseListRepository.java
  src/main/java/homeTry/exerciseList/service/ExerciseListService.java
Labels: :bug: bug, :sparkles: feat

#71 [Week4] 토큰 검증 강화 및 코드 리뷰 반영
  src/main/java/homeTry/auth/JwtAuth.java
  src/main/java/homeTry/auth/kakaoAuth/config/KakaoAuthConfig.java
  src/main/java/homeTry/auth/kakaoAuth/service/KakaoTokenService.java
  src/main/resources/application-kakao-login.properties
Labels: :hammer: enhancement, :recycle: refactor

#73 [Week4] diaryRepository 쿼리문 수정
  src/main/java/homeTry/diary/repository/DiaryRepository.java
Labels: :bug: bug

#75 [Week4] refactor: Member 기본키 변경
  src/main/java/homeTry/member/model/entity/Member.java
Labels: :recycle: refactor

#78 [Week4] Diary와 Member의 연관관계 구현
  src/main/java/homeTry/diary/model/entity/Diary.java
  src/main/java/homeTry/diary/repository/DiaryRepository.java
  src/main/java/homeTry/diary/service/DiaryService.java
Labels: :sparkles: feat

#80 [Week4] refactor: Member 기본키 email -> id로 변경
  src/main/java/homeTry/member/controller/MemberController.java
Labels: :construction: incomplete
