Repository kakao-tech-campus-2nd-step3/Team17_BE, pull requests merged in 2024-10, with the labels that each got.

#91 [ Week5] Service 분리 및 특정 하루 운동 기록 반환 구현
  src/main/java/homeTry/exerciseList/dto/ExerciseResponse.java
  src/main/java/homeTry/exerciseList/model/entity/Exercise.java
  src/main/java/homeTry/exerciseList/model/entity/ExerciseTime.java
  src/main/java/homeTry/exerciseList/repository/ExerciseRepository.java
  src/main/java/homeTry/exerciseList/repository/ExerciseTimeRepository.java
  src/main/java/homeTry/exerciseList/service/ExerciseHistoryService.java
  src/main/java/homeTry/exerciseList/service/ExerciseSchedulerService.java
  src/main/java/homeTry/exerciseList/service/ExerciseService.java
  src/main/java/homeTry/exerciseList/service/ExerciseTimeService.java
Labels: :sparkles: feat, :recycle: refactor

#92 [Week5] 리팩토링 및 Diary 예외처리 기능 구현
  src/main/java/homeTry/diary/controller/DiaryController.java
  src/main/java/homeTry/diary/dto/DiaryDto.java
  src/main/java/homeTry/diary/exception/DiaryErrorType.java
  src/main/java/homeTry/diary/exception/DiaryNotFoundException.java
  src/main/java/homeTry/diary/exception/MemoBlankException.java
  src/main/java/homeTry/diary/model/vo/Memo.java
  src/main/java/homeTry/diary/repository/DiaryRepository.java
  src/main/java/homeTry/diary/service/DiaryService.java
  src/main/java/homeTry/mainPage/controller/MainPageController.java
  src/main/java/homeTry/mainPage/dto/response/MainPageResponse.java
  src/main/java/homeTry/mainPage/service/MainPageService.java
Labels: :sparkles: feat, :recycle: refactor

#94 [Week5] MainPageService 구현
  src/main/java/homeTry/diary/dto/DiaryDto.java
  src/main/java/homeTry/diary/service/DiaryService.java
  src/main/java/homeTry/mainPage/dto/response/MainPageResponse.java
  src/main/java/homeTry/mainPage/service/MainPageService.java
Labels: :sparkles: feat

#95 [Week5] Member Controller 리팩터링
  src/main/java/homeTry/member/controller/MemberController.java
  src/main/java/homeTry/member/service/MemberService.java
Labels: :recycle: refactor

#97 [Week5] 예외 처리 고도화
  src/main/java/homeTry/auth/LoginMemberArgumentResolver.java
  src/main/java/homeTry/auth/exception/AuthErrorType.java
  src/main/java/homeTry/auth/exception/badRequestException/InvalidAuthCodeException.java
  src/main/java/homeTry/auth/exception/badRequestException/InvalidTokenException.java
  src/main/java/homeTry/auth/exception/internalServerException/HomeTryServerException.java
  src/main/java/homeTry/auth/exception/internalServerException/KakaoAuthServerException.java
  src/main/java/homeTry/auth/kakaoAuth/dto/KakaoErrorResponseDTO.java
  src/main/java/homeTry/auth/kakaoAuth/service/KakaoAuthService.java
  src/main/java/homeTry/auth/kakaoAuth/service/KakaoTokenService.java
  src/main/java/homeTry/exception/clientException/BadRequestException.java
  src/main/java/homeTry/exception/clientException/UserNotFoundException.java
  src/main/java/homeTry/exception/serverException/InternalServerException.java
  src/main/java/homeTry/member/exception/MemberErrorType.java
  src/main/java/homeTry/member/exception/badRequestException/BadArgumentException.java
  src/main/java/homeTry/member/exception/badRequestException/LoginFailedException.java
  src/main/java/homeTry/member/exception/badRequestException/MemberNotFoundException.java
  src/main/java/homeTry/member/exception/badRequestException/RegisterEmailConflictException.java
  src/main/java/homeTry/member/exception/internalServerException/UniqueKeyViolatonException.java
  src/main/java/homeTry/member/exception/internalServerException/UnknownFatalException.java
  src/main/java/homeTry/member/service/MemberService.java
Labels: :hammer: enhancement, :recycle: refactor

#98 [Week5] 토큰 생성 에러 해결
  src/main/java/homeTry/auth/kakaoAuth/service/KakaoAuthService.java
  src/main/java/homeTry/member/exception/badRequestException/BadArgumentException.java
  src/main/java/homeTry/member/repository/MemberRepository.java
Labels: :bug: bug

#104 [Week5] refactor: MainPageService 리팩토링
  src/main/java/homeTry/mainPage/service/MainPageService.java
Labels: :recycle: refactor

#105 [Week5] 사용하는 DTO 변수 수정
  src/main/java/homeTry/exerciseList/service/ExerciseHistoryService.java
  src/main/java/homeTry/exerciseList/service/ExerciseTimeService.java
Labels: :recycle: refactor

#112 [Week5] 코드리뷰 반영으로 인한 Member 기능 리팩터링
  src/main/java/homeTry/auth/kakaoAuth/service/KakaoAuthService.java
  src/main/java/homeTry/auth/kakaoAuth/service/KakaoTokenService.java
  src/main/java/homeTry/member/controller/MemberController.java
  src/main/java/homeTry/member/dto/MemberDTO.java
  src/main/java/homeTry/member/model/entity/Member.java
  src/main/java/homeTry/member/model/vo/Email.java
  src/main/java/homeTry/member/model/vo/Nickname.java
  src/main/java/homeTry/member/model/vo/Password.java
  src/main/java/homeTry/member/repository/MemberRepository.java
  src/main/java/homeTry/member/service/MemberService.java
  src/main/resources/data.sql
Labels: :recycle: refactor

#113 [Week5] DTO 필드 JsonProperty -> JsonNaming
  src/main/java/homeTry/auth/kakaoAuth/dto/KakaoErrorResponseDTO.java
  src/main/java/homeTry/auth/kakaoAuth/dto/KakaoMemberInfoDTO.java
  src/main/java/homeTry/auth/kakaoAuth/dto/TokenResponseDTO.java
  src/main/java/homeTry/member/exception/badRequestException/BadArgumentException.java
  src/main/java/homeTry/member/exception/internalServerException/UnknownFatalException.java
Labels: :recycle: refactor

#119 [Week6] DTO 이름 리팩터링 & Base Entity 상속
  src/main/java/homeTry/common/auth/kakaoAuth/dto/response/KakaoErrorResponse.java
  src/main/java/homeTry/common/auth/kakaoAuth/dto/response/KakaoMemberInfoResponse.java
  src/main/java/homeTry/common/auth/kakaoAuth/dto/response/TokenResponse.java
  src/main/java/homeTry/common/auth/kakaoAuth/service/KakaoTokenService.java
  src/main/java/homeTry/exerciseList/service/ExerciseSchedulerService.java
  src/main/java/homeTry/member/controller/MemberController.java
  src/main/java/homeTry/member/dto/ChangeNicknameDTO.java
  src/main/java/homeTry/member/dto/MemberDTO.java
  src/main/java/homeTry/member/dto/request/ChangeNicknameRequest.java
  src/main/java/homeTry/member/dto/response/MyPageResponse.java
  src/main/java/homeTry/member/model/entity/Member.java
  src/main/java/homeTry/member/service/MemberService.java
  src/main/resources/data.sql
Labels: :recycle: refactor

#120 [Week6] 리뷰 기반 리팩토링 및 BaseEntity 상속 기능 추가
  src/main/java/homeTry/diary/controller/DiaryController.java
  src/main/java/homeTry/diary/dto/DiaryDto.java
  src/main/java/homeTry/diary/dto/request/DiaryRequest.java
  src/main/java/homeTry/diary/model/entity/Diary.java
  src/main/java/homeTry/diary/model/vo/Memo.java
  src/main/java/homeTry/diary/repository/DiaryRepository.java
  src/main/java/homeTry/diary/service/DiaryService.java
  src/main/java/homeTry/mainPage/controller/MainPageController.java
  src/main/java/homeTry/mainPage/dto/request/MainPageRequest.java
  src/main/java/homeTry/mainPage/dto/response/MainPageResponse.java
  src/main/java/homeTry/mainPage/service/MainPageService.java
Labels: :sparkles: feat, :recycle: refactor

#121 [Week6] Config 파일 immutable 하도록 리팩터링
  src/main/java/homeTry/common/auth/kakaoAuth/config/KakaoAuthConfig.java
  src/main/java/homeTry/common/auth/kakaoAuth/config/KakaoAuthConfigRegistrar.java
  src/main/java/homeTry/common/auth/kakaoAuth/service/KakaoTokenService.java
Labels: :recycle: refactor

#124 [Week6] Member 기능 - 피드백 반영
  src/main/java/homeTry/member/repository/MemberRepository.java
  src/main/java/homeTry/member/service/MemberService.java
Labels: :recycle: refactor

#125 [Week6] MainPageResponse내 ExerciseResponse 경로 수정
  src/main/java/homeTry/mainPage/dto/response/MainPageResponse.java
Labels: :recycle: refactor

#123 [Week6] 피드백 반영
  src/main/java/homeTry/common/constants/DateTimeUtil.java
  src/main/java/homeTry/exerciseList/controller/ExerciseController.java
  src/main/java/homeTry/exerciseList/dto/request/ExerciseRequest.java
  src/main/java/homeTry/exerciseList/dto/response/ExerciseResponse.java
  src/main/java/homeTry/exerciseList/model/entity/Exercise.java
  src/main/java/homeTry/exerciseList/model/entity/ExerciseHistory.java
  src/main/java/homeTry/exerciseList/model/entity/ExerciseTime.java
  src/main/java/homeTry/exerciseList/repository/ExerciseRepository.java
  src/main/java/homeTry/exerciseList/service/ExerciseHistoryService.java
  src/main/java/homeTry/exerciseList/service/ExerciseService.java
  src/main/java/homeTry/exerciseList/service/ExerciseTimeService.java
Labels: :recycle: refactor, :construction: incomplete

#126 [Week6] feat: GlobalExceptionHandler 추가
  src/main/java/homeTry/common/exception/GlobalExceptionHandler.java
  src/main/java/homeTry/common/exception/dto/response/ErrorResponse.java
Labels: :sparkles: feat

#128 [Week6] 운동 기능 예외 처리 추가 및 DTO에서 시간 반환 String으로 처리하도록 수정
  src/main/java/homeTry/exerciseList/dto/response/ExerciseResponse.java
  src/main/java/homeTry/exerciseList/exception/ExerciseErrorType.java
  src/main/java/homeTry/exerciseList/exception/badRequestException/ExerciseInProgressException.java
  src/main/java/homeTry/exerciseList/service/ExerciseService.java
Labels: :recycle: refactor

#132 [Week6] 쉘 스크립트 추가
  deploy.sh
Labels: :sparkles: feat

#140 [Week6] CORS 테스트 추가
  src/test/java/homeTry/common/config/CorsTest.java
Labels: :sparkles: feat

#143 [Week7-8] 운동 이름 validation 리팩토링
  src/main/java/homeTry/exerciseList/controller/ExerciseController.java
  src/main/java/homeTry/exerciseList/dto/request/ExerciseRequest.java
Labels: :recycle: refactor

#145 [Week8] refactor: 유효성 검사 리팩토링 및 코드 리뷰 반영
  src/main/java/homeTry/diary/dto/request/DiaryRequest.java
  src/main/java/homeTry/diary/exception/BadRequestException/MemoBlankException.java
  src/main/java/homeTry/diary/exception/BadRequestException/MemoTooLongException.java
  src/main/java/homeTry/diary/exception/DiaryErrorType.java
  src/main/java/homeTry/diary/model/vo/Memo.java
  src/main/java/homeTry/mainPage/dto/request/MainPageRequest.java
  src/main/java/homeTry/mainPage/exception/BadRequestException/InvalidDateException.java
  src/main/java/homeTry/mainPage/exception/MainPageErrorType.java
  src/main/java/homeTry/mainPage/service/MainPageService.java
Labels: :recycle: refactor

#154 [Week9] Member - 출석일 수 기능 구현
  src/main/java/homeTry/member/dto/response/MyPageResponse.java
  src/main/java/homeTry/member/model/entity/Member.java
  src/main/java/homeTry/member/service/MemberService.java
  src/main/resources/data.sql
Labels: :sparkles: feat

#156 [Week9] GlobalExceptionHandler 리팩토링
  src/main/java/homeTry/common/exception/CommonErrorType.java
  src/main/java/homeTry/common/exception/GlobalExceptionHandler.java
Labels: :recycle: refactor

#155 [Week9] 운동 스케줄러에 멤버 출석일 증가 구현
  src/main/java/homeTry/exerciseList/model/entity/ExerciseTime.java
  src/main/java/homeTry/exerciseList/service/ExerciseSchedulerService.java
  src/main/java/homeTry/exerciseList/service/ExerciseService.java
Labels: :sparkles: feat, :recycle: refactor

#160 [Week9] 상품 태그 관련 기능 수정
  src/main/java/homeTry/product/model/entity/ProductTag.java
  src/main/java/homeTry/product/model/vo/ProductTagName.java
  src/main/java/homeTry/product/service/ProductService.java
  src/main/java/homeTry/tag/model/entity/ProductTag.java
  src/main/java/homeTry/tag/service/ProductTagService.java
Labels: :recycle: refactor

#161 [Week9] 채팅 기능 구현
  build.gradle
  src/main/java/homeTry/chatting/config/ChattingConfig.java
  src/main/java/homeTry/chatting/controller/ChattingController.java
  src/main/java/homeTry/chatting/dto/request/ChattingMessageRequest.java
  src/main/java/homeTry/chatting/dto/response/ChattingMessageResponse.java
  src/main/java/homeTry/chatting/exception/ChattingErrorType.java
  src/main/java/homeTry/chatting/exception/ChattingExceptionHandler.java
  src/main/java/homeTry/chatting/exception/badRequestException/InvalidChattingTokenException.java
  src/main/java/homeTry/chatting/exception/badRequestException/InvalidTeamIdException.java
  src/main/java/homeTry/chatting/interceptor/StompInterceptor.java
  src/main/java/homeTry/chatting/model/entity/Chatting.java
  src/main/java/homeTry/chatting/repository/ChattingRepository.java
  src/main/java/homeTry/chatting/service/ChattingService.java
  src/main/java/homeTry/common/config/WebMvcConfig.java
Labels: :sparkles: feat, :construction: incomplete

#162 [Week9] 운동 시간 관련 수정
  src/main/java/homeTry/common/converter/DurationToLongConverter.java
  src/main/java/homeTry/exerciseList/dto/response/ExerciseResponse.java
  src/main/java/homeTry/exerciseList/model/entity/ExerciseHistory.java
  src/main/java/homeTry/exerciseList/model/entity/ExerciseTime.java
  src/main/java/homeTry/exerciseList/service/ExerciseHistoryService.java
  src/main/java/homeTry/exerciseList/service/ExerciseTimeService.java
Labels: :recycle: refactor, :construction: incomplete

#163 [Week9] 운동 시간 리팩터링
  src/main/java/homeTry/member/dto/response/MyPageResponse.java
  src/main/java/homeTry/member/service/MemberService.java
Labels: :recycle: refactor

#164 [Week9] Duration -> Long으로 형변환
  src/main/java/homeTry/mainPage/dto/response/MainPageResponse.java
  src/main/java/homeTry/team/dto/RankingDTO.java
  src/main/java/homeTry/team/dto/response/RankingResponse.java
  src/main/java/homeTry/team/service/TeamService.java
Labels: :recycle: refactor

#167 [Week9] Chatting - 잘못된 토큰 예외 처리 구현
  build.gradle
  src/main/java/homeTry/chatting/config/ChattingConfig.java
  src/main/java/homeTry/chatting/controller/ChattingController.java
  src/main/java/homeTry/chatting/exception/ChattingErrorType.java
  src/main/java/homeTry/chatting/exception/handler/ChattingExceptionHandler.java
  src/main/java/homeTry/chatting/exception/handler/StompInterceptorErrorHandler.java
  src/main/java/homeTry/chatting/interceptor/StompInterceptor.java
  src/main/java/homeTry/common/auth/LoginMemberArgumentResolver.java
  src/main/java/homeTry/common/config/WebMvcConfig.java
Labels: :sparkles: feat

#165 [Week9] 상품 관리 기능 구현
  src/main/java/homeTry/product/controller/AdminProductController.java
  src/main/java/homeTry/product/dto/request/ProductRequest.java
  src/main/java/homeTry/product/exception/ProductErrorType.java
  src/main/java/homeTry/product/exception/badRequestException/ProductNotFoundException.java
  src/main/java/homeTry/product/repository/ProductRepository.java
  src/main/java/homeTry/product/service/AdminProductService.java
Labels: :sparkles: feat

#168 [Week9] 운동 관련 엔티티에 인덱싱 추가
  src/main/java/homeTry/exerciseList/model/entity/Exercise.java
  src/main/java/homeTry/exerciseList/model/entity/ExerciseHistory.java
  src/main/java/homeTry/exerciseList/model/entity/ExerciseTime.java
Labels: :recycle: refactor
